### PR TITLE
Add/Welcome Page

### PR DESCRIPTION
**Pull request by Grgkalunta**
Need any Improvements?

### CODE REVIEW

**Review by Hybrid-Codes — CHANGES_REQUESTED** [review]
Branch name is incorrect:

- no capital letters 
- your name is first word
- / to separate name from what the branch is for eg: greg/
- dash to separate words eg: add-welcome-page

Styling must not be done in page:

- app.css to style, this is in the wwwroot folder
-  make use of button classes and heading classes so that you can style them

**Comment by CodePidgy** [comment]
I fixed the styling of the code

**Comment by CodePidgy** [comment]
Don't worry about the branch name for this run, since you can't change it now

**Comment by Hybrid-Codes** [comment]
Alright, the css still has to be added to app.css and not to the actual page itself

**Comment by Grgkalunta** [comment]
Are you guys able to see the CSS style or Background when you run the website?

**Pull request closed without merging**
