### PR TITLE
Welcomepage adjustment 2

### PR DESCRIPTION
**Pull request by Grgkalunta**

### CODE REVIEW

**Comment by Hybrid-Codes** [comment]
This is a satisfactory description for the IMEI however it is not centred underneath the search bar and this makes it look strange. 

Also there is not outline for the search bar and which is still inconsistent with the design and I still see you have not implemented fluent validation please implement everything listed.

**Comment by Hybrid-Codes** [comment]
image
Also your search bar and box is not compatible with mobile screen sizes as I checked in inspect element.

**Comment by Grgkalunta** [comment]
> This is a satisfactory description for the IMEI however it is not centred underneath the search bar and this makes it look strange. 
> 
> Also there is not outline for the search bar and which is still inconsistent with the design and I still see you have not implemented fluent validation please implement everything listed.


lol bro

**Comment by Hybrid-Codes** [comment]
> > This is a satisfactory description for the IMEI however it is not centred underneath the search bar and this makes it look strange.
> > Also there is not outline for the search bar and which is still inconsistent with the design and I still see you have not implemented fluent validation please implement everything listed.
> 
> lol bro

Lol? This is an official pull request you don't use that type of language and tone here. Please solve the problems you have been assigned.

**Pull request merged**
