### PR TITLE
Add css

### PR DESCRIPTION
**Pull request by CodePidgy**

### CODE REVIEW

**Comment by CodePidgy** [comment]
Re-created the PR

**Comment by Hybrid-Codes** [comment]
Bruh its still the same thing.

**Comment by Hybrid-Codes** [comment]
Nothing has changed

**Comment by CodePidgy** [comment]
This PR is completely redundant. It add's nothing but the CSS we had from the prototype. The only thing genuinely added which was useful is the map background, which we have already implemented as well. I am going to close this PR

**Pull request closed without merging**
